// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZCVKe6clgQHbEr-Xe-vxsgwXamk4yI40',
    appId: '1:1077629936027:web:f9b521f9c3c8976540413e',
    messagingSenderId: '1077629936027',
    projectId: 'healthtracker-lazyname',
    authDomain: 'healthtracker-lazyname.firebaseapp.com',
    storageBucket: 'healthtracker-lazyname.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWAKBu7Hy5wkh7xzkWAwDjxGGS82NSYz0',
    appId: '1:1077629936027:android:72cd68543ad67cff40413e',
    messagingSenderId: '1077629936027',
    projectId: 'healthtracker-lazyname',
    storageBucket: 'healthtracker-lazyname.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZCVKe6clgQHbEr-Xe-vxsgwXamk4yI40',
    appId: '1:1077629936027:web:a100908cda69839540413e',
    messagingSenderId: '1077629936027',
    projectId: 'healthtracker-lazyname',
    authDomain: 'healthtracker-lazyname.firebaseapp.com',
    storageBucket: 'healthtracker-lazyname.firebasestorage.app',
  );
}
